# Generated by Django 6.0.3 on 2026-04-15 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0005_remove_table_is_available_remove_table_is_combinable_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablesize',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seatingtype',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_seating_types', to='Restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='tablesize',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_table_sizes', to='Restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='seating_types',
            field=models.ManyToManyField(blank=True, related_name='offering_restaurants', to='Restaurants.seatingtype'),
        ),
        migrations.AlterField(
            model_name='seatingtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='seatingtype',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tablesize',
            unique_together={('restaurant', 'capacity', 'size')},
        ),
    ]
