# Generated by Django 6.0.3 on 2026-04-21 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0006_alter_tablesize_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='adjusted_closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='adjusted_opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('opening_hour', models.TimeField(blank=True, null=True)),
                ('closing_hour', models.TimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='Restaurants.restaurant')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
    ]
