# Generated by Django 6.0.3 on 2026-04-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersHandling', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantstaff',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Owner'), ('STAFF', 'Staff')], max_length=10),
        ),
    ]
