# Generated by Django 6.0.3 on 2026-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name_on_the_card',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
