# Generated by Django 6.0.3 on 2026-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_remove_booking_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
