# Generated by Django 6.0.3 on 2026-04-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0003_booking_locked_at_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
