# Generated by Django 6.0.3 on 2026-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0004_alter_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='locked_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
